version: '3.8'

services:
  # Angular Admin App
  job-admin:
    build:
      context: ./apps/job-admin
    container_name: job-admin
    ports:
      - "6080:80"
    networks:
      - ai-job-board-net

  # Next.js Public App
  job-public:
    build:
      context: ./apps/job-public
    container_name: job-public
    ports:
      - "6081:3000"
    networks:
      - ai-job-board-net

  # Node.js AI Service (expose both its own port and Dapr's HTTP port)
  ai-service:
    build:
      context: ./services/ai-service
    container_name: ai-service
    ports:
      - "6082:6082"  # AI service itself
      - "6083:6083"  # Dapr HTTP API port
    environment:
      - PORT=6082
    networks:
      - ai-job-board-net

  # Dapr sidecar shares network with ai-service
  dapr-sidecar:
    image: "daprio/daprd:latest"
    container_name: dapr-sidecar
    depends_on:
      - ai-service
    network_mode: "service:ai-service"
    command: [
      "./daprd",
      "--app-id", "ai-service",
      "--app-port", "6082",
      "--dapr-http-port", "6083",
      "--log-level", "debug"
    ]

networks:
  ai-job-board-net:
    name: ai-job-board-net
