version: '3.9'

services:
  job-admin:
    image: registry.eelkhair.net/job-admin:latest
    ports:
      - "6080:80"
    restart: unless-stopped
    networks:
      - ai-job-board-net

  job-public:
    image: registry.eelkhair.net/job-public:latest
    ports:
      - "6081:3000"
    restart: unless-stopped
    networks:
      - ai-job-board-net

  ai-service:
    image: registry.eelkhair.net/ai-service:latest
    container_name: ai-service
    ports:
      - "6082:6082"  # AI service itself
      - "6083:6083"  # Dapr HTTP API port
    environment:
      - PORT=6082
    networks:
      - ai-job-board-net

  ai-service-sidecar:
    image: "daprio/daprd:latest"
    container_name: ai-services-sidecar
    depends_on:
      - ai-service
    network_mode: "service:ai-service"
    command: [
      "./daprd",
      "--app-id", "ai-service",
      "--app-port", "6082",
      "--dapr-http-port", "6083",
      "--log-level", "debug"
    ]

  job-api:
    build:
      context: ./services/job-api/
    image: registry.eelkhair.net/job-api:latest
    ports:
      - "6084:8080"
      - "6085:6085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - ai-job-board-net

  job-api-sidecar:
    image: "daprio/daprd:latest"
    container_name: "job-api-side-car"
    depends_on:
      - job-api
    network_mode: "service:job-api"
    command: [
      "./daprd",
      "--app-id", "job-api",
      "--app-port", "8080",
      "--dapr-http-port", "6085",
      "--log-level", "debug"
    ]
    
networks:
  ai-job-board-net:
    name: ai-job-board-net
