apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: appconfig-monolith-mcp
spec:
  type: configuration.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisDb
      value: "1"
scopes:
  - monolith-mcp
