apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "./DaprComponents/secrets/secrets.json"
