FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY portfolio.html /usr/share/nginx/html/portfolio.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY profile.jpg /usr/share/nginx/html/profile.jpg
COPY images/ /usr/share/nginx/html/images/
EXPOSE 80
