apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2clientcredentials
spec:
  type: middleware.http.oauth2clientcredentials
  version: v1
  metadata:
    - name: clientId
      secretKeyRef:
        name: shared
        key: Auth0:SwaggerClientId

    - name: clientSecret
      secretKeyRef:
        name: shared
        key: Auth0:SwaggerClientSecret

    - name: scopes
      value: "read:users read:companies write:users write:companies read:jobs write:jobs"

    - name: tokenURL
      value: "https://elkhair-dev.us.auth0.com/oauth/token"

    - name: headerName
      value: "Authorization"

    - name: endpointParamsQuery
      value: "audience=https://job-board.eelkhair.net"
auth:
  secretStore: "vault"